# Generated by Django 5.2.5 on 2026-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='chain',
            field=models.CharField(default='cardano', max_length=64),
        ),
    ]
